---
driver:
  name: docker 

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
    run_list:
    - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[pokenum::default]

    attributes:

